/*
 * External method calls:
 *   Lnet/minecraft/client/render/RenderLayers;cutout()Lnet/minecraft/client/render/RenderLayer;
 *   Lnet/minecraft/client/render/RenderLayers;solid()Lnet/minecraft/client/render/RenderLayer;
 *   Lnet/minecraft/client/render/RenderLayers;translucentMovingBlock()Lnet/minecraft/client/render/RenderLayer;
 *   Lnet/minecraft/client/render/RenderLayers;tripwire()Lnet/minecraft/client/render/RenderLayer;
 *   Lnet/minecraft/block/CopperBlockSet;forEach(Ljava/util/function/Consumer;)V
 *   Lnet/minecraft/util/Util;make(Ljava/lang/Object;Ljava/util/function/Consumer;)Ljava/lang/Object;
 */
package net.minecraft.client.render;

import com.google.common.collect.Maps;
import java.util.Map;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.block.Block;
import net.minecraft.block.BlockState;
import net.minecraft.block.Blocks;
import net.minecraft.block.LeavesBlock;
import net.minecraft.client.render.BlockRenderLayer;
import net.minecraft.client.render.RenderLayer;
import net.minecraft.client.render.RenderLayers;
import net.minecraft.client.render.TexturedRenderLayers;
import net.minecraft.fluid.Fluid;
import net.minecraft.fluid.FluidState;
import net.minecraft.fluid.Fluids;
import net.minecraft.util.Util;

@Environment(value=EnvType.CLIENT)
public class BlockRenderLayers {
    private static final Map<Block, BlockRenderLayer> BLOCKS = Util.make(Maps.newHashMap(), map -> {
        BlockRenderLayer lv = BlockRenderLayer.TRIPWIRE;
        map.put(Blocks.TRIPWIRE, lv);
        BlockRenderLayer lv2 = BlockRenderLayer.CUTOUT;
        map.put(Blocks.GRASS_BLOCK, lv2);
        map.put(Blocks.IRON_BARS, lv2);
        Blocks.COPPER_BARS.forEach(block -> map.put(block, lv2));
        map.put(Blocks.TRIPWIRE_HOOK, lv2);
        map.put(Blocks.HOPPER, lv2);
        map.put(Blocks.IRON_CHAIN, lv2);
        Blocks.COPPER_CHAINS.forEach(block -> map.put(block, lv2));
        map.put(Blocks.JUNGLE_LEAVES, lv2);
        map.put(Blocks.OAK_LEAVES, lv2);
        map.put(Blocks.SPRUCE_LEAVES, lv2);
        map.put(Blocks.ACACIA_LEAVES, lv2);
        map.put(Blocks.CHERRY_LEAVES, lv2);
        map.put(Blocks.BIRCH_LEAVES, lv2);
        map.put(Blocks.DARK_OAK_LEAVES, lv2);
        map.put(Blocks.PALE_OAK_LEAVES, lv2);
        map.put(Blocks.AZALEA_LEAVES, lv2);
        map.put(Blocks.FLOWERING_AZALEA_LEAVES, lv2);
        map.put(Blocks.MANGROVE_ROOTS, lv2);
        map.put(Blocks.MANGROVE_LEAVES, lv2);
        map.put(Blocks.OAK_SAPLING, lv2);
        map.put(Blocks.SPRUCE_SAPLING, lv2);
        map.put(Blocks.BIRCH_SAPLING, lv2);
        map.put(Blocks.JUNGLE_SAPLING, lv2);
        map.put(Blocks.ACACIA_SAPLING, lv2);
        map.put(Blocks.CHERRY_SAPLING, lv2);
        map.put(Blocks.DARK_OAK_SAPLING, lv2);
        map.put(Blocks.PALE_OAK_SAPLING, lv2);
        map.put(Blocks.WHITE_BED, lv2);
        map.put(Blocks.ORANGE_BED, lv2);
        map.put(Blocks.MAGENTA_BED, lv2);
        map.put(Blocks.LIGHT_BLUE_BED, lv2);
        map.put(Blocks.YELLOW_BED, lv2);
        map.put(Blocks.LIME_BED, lv2);
        map.put(Blocks.PINK_BED, lv2);
        map.put(Blocks.GRAY_BED, lv2);
        map.put(Blocks.LIGHT_GRAY_BED, lv2);
        map.put(Blocks.CYAN_BED, lv2);
        map.put(Blocks.PURPLE_BED, lv2);
        map.put(Blocks.BLUE_BED, lv2);
        map.put(Blocks.BROWN_BED, lv2);
        map.put(Blocks.GREEN_BED, lv2);
        map.put(Blocks.RED_BED, lv2);
        map.put(Blocks.BLACK_BED, lv2);
        map.put(Blocks.POWERED_RAIL, lv2);
        map.put(Blocks.DETECTOR_RAIL, lv2);
        map.put(Blocks.COBWEB, lv2);
        map.put(Blocks.SHORT_GRASS, lv2);
        map.put(Blocks.FERN, lv2);
        map.put(Blocks.BUSH, lv2);
        map.put(Blocks.DEAD_BUSH, lv2);
        map.put(Blocks.SHORT_DRY_GRASS, lv2);
        map.put(Blocks.TALL_DRY_GRASS, lv2);
        map.put(Blocks.SEAGRASS, lv2);
        map.put(Blocks.TALL_SEAGRASS, lv2);
        map.put(Blocks.DANDELION, lv2);
        map.put(Blocks.OPEN_EYEBLOSSOM, lv2);
        map.put(Blocks.CLOSED_EYEBLOSSOM, lv2);
        map.put(Blocks.POPPY, lv2);
        map.put(Blocks.BLUE_ORCHID, lv2);
        map.put(Blocks.ALLIUM, lv2);
        map.put(Blocks.AZURE_BLUET, lv2);
        map.put(Blocks.RED_TULIP, lv2);
        map.put(Blocks.ORANGE_TULIP, lv2);
        map.put(Blocks.WHITE_TULIP, lv2);
        map.put(Blocks.PINK_TULIP, lv2);
        map.put(Blocks.OXEYE_DAISY, lv2);
        map.put(Blocks.CORNFLOWER, lv2);
        map.put(Blocks.WITHER_ROSE, lv2);
        map.put(Blocks.LILY_OF_THE_VALLEY, lv2);
        map.put(Blocks.BROWN_MUSHROOM, lv2);
        map.put(Blocks.RED_MUSHROOM, lv2);
        map.put(Blocks.TORCH, lv2);
        map.put(Blocks.WALL_TORCH, lv2);
        map.put(Blocks.SOUL_TORCH, lv2);
        map.put(Blocks.SOUL_WALL_TORCH, lv2);
        map.put(Blocks.COPPER_TORCH, lv2);
        map.put(Blocks.COPPER_WALL_TORCH, lv2);
        map.put(Blocks.FIRE, lv2);
        map.put(Blocks.SOUL_FIRE, lv2);
        map.put(Blocks.SPAWNER, lv2);
        map.put(Blocks.TRIAL_SPAWNER, lv2);
        map.put(Blocks.VAULT, lv2);
        map.put(Blocks.WHEAT, lv2);
        map.put(Blocks.OAK_DOOR, lv2);
        map.put(Blocks.LADDER, lv2);
        map.put(Blocks.RAIL, lv2);
        map.put(Blocks.IRON_DOOR, lv2);
        map.put(Blocks.REDSTONE_TORCH, lv2);
        map.put(Blocks.REDSTONE_WALL_TORCH, lv2);
        map.put(Blocks.CACTUS, lv2);
        map.put(Blocks.SUGAR_CANE, lv2);
        map.put(Blocks.REPEATER, lv2);
        map.put(Blocks.OAK_TRAPDOOR, lv2);
        map.put(Blocks.SPRUCE_TRAPDOOR, lv2);
        map.put(Blocks.BIRCH_TRAPDOOR, lv2);
        map.put(Blocks.JUNGLE_TRAPDOOR, lv2);
        map.put(Blocks.ACACIA_TRAPDOOR, lv2);
        map.put(Blocks.CHERRY_TRAPDOOR, lv2);
        map.put(Blocks.DARK_OAK_TRAPDOOR, lv2);
        map.put(Blocks.PALE_OAK_TRAPDOOR, lv2);
        map.put(Blocks.CRIMSON_TRAPDOOR, lv2);
        map.put(Blocks.WARPED_TRAPDOOR, lv2);
        map.put(Blocks.MANGROVE_TRAPDOOR, lv2);
        map.put(Blocks.BAMBOO_TRAPDOOR, lv2);
        map.put(Blocks.COPPER_TRAPDOOR, lv2);
        map.put(Blocks.EXPOSED_COPPER_TRAPDOOR, lv2);
        map.put(Blocks.WEATHERED_COPPER_TRAPDOOR, lv2);
        map.put(Blocks.OXIDIZED_COPPER_TRAPDOOR, lv2);
        map.put(Blocks.WAXED_COPPER_TRAPDOOR, lv2);
        map.put(Blocks.WAXED_EXPOSED_COPPER_TRAPDOOR, lv2);
        map.put(Blocks.WAXED_WEATHERED_COPPER_TRAPDOOR, lv2);
        map.put(Blocks.WAXED_OXIDIZED_COPPER_TRAPDOOR, lv2);
        map.put(Blocks.ATTACHED_PUMPKIN_STEM, lv2);
        map.put(Blocks.ATTACHED_MELON_STEM, lv2);
        map.put(Blocks.PUMPKIN_STEM, lv2);
        map.put(Blocks.MELON_STEM, lv2);
        map.put(Blocks.VINE, lv2);
        map.put(Blocks.PALE_MOSS_CARPET, lv2);
        map.put(Blocks.PALE_HANGING_MOSS, lv2);
        map.put(Blocks.GLOW_LICHEN, lv2);
        map.put(Blocks.RESIN_CLUMP, lv2);
        map.put(Blocks.LILY_PAD, lv2);
        map.put(Blocks.NETHER_WART, lv2);
        map.put(Blocks.BREWING_STAND, lv2);
        map.put(Blocks.COCOA, lv2);
        map.put(Blocks.FLOWER_POT, lv2);
        map.put(Blocks.POTTED_OAK_SAPLING, lv2);
        map.put(Blocks.POTTED_SPRUCE_SAPLING, lv2);
        map.put(Blocks.POTTED_BIRCH_SAPLING, lv2);
        map.put(Blocks.POTTED_JUNGLE_SAPLING, lv2);
        map.put(Blocks.POTTED_ACACIA_SAPLING, lv2);
        map.put(Blocks.POTTED_CHERRY_SAPLING, lv2);
        map.put(Blocks.POTTED_DARK_OAK_SAPLING, lv2);
        map.put(Blocks.POTTED_PALE_OAK_SAPLING, lv2);
        map.put(Blocks.POTTED_MANGROVE_PROPAGULE, lv2);
        map.put(Blocks.POTTED_FERN, lv2);
        map.put(Blocks.POTTED_DANDELION, lv2);
        map.put(Blocks.POTTED_POPPY, lv2);
        map.put(Blocks.POTTED_OPEN_EYEBLOSSOM, lv2);
        map.put(Blocks.POTTED_CLOSED_EYEBLOSSOM, lv2);
        map.put(Blocks.POTTED_BLUE_ORCHID, lv2);
        map.put(Blocks.POTTED_ALLIUM, lv2);
        map.put(Blocks.POTTED_AZURE_BLUET, lv2);
        map.put(Blocks.POTTED_RED_TULIP, lv2);
        map.put(Blocks.POTTED_ORANGE_TULIP, lv2);
        map.put(Blocks.POTTED_WHITE_TULIP, lv2);
        map.put(Blocks.POTTED_PINK_TULIP, lv2);
        map.put(Blocks.POTTED_OXEYE_DAISY, lv2);
        map.put(Blocks.POTTED_CORNFLOWER, lv2);
        map.put(Blocks.POTTED_LILY_OF_THE_VALLEY, lv2);
        map.put(Blocks.POTTED_WITHER_ROSE, lv2);
        map.put(Blocks.POTTED_RED_MUSHROOM, lv2);
        map.put(Blocks.POTTED_BROWN_MUSHROOM, lv2);
        map.put(Blocks.POTTED_DEAD_BUSH, lv2);
        map.put(Blocks.POTTED_CACTUS, lv2);
        map.put(Blocks.POTTED_AZALEA_BUSH, lv2);
        map.put(Blocks.POTTED_FLOWERING_AZALEA_BUSH, lv2);
        map.put(Blocks.POTTED_TORCHFLOWER, lv2);
        map.put(Blocks.CARROTS, lv2);
        map.put(Blocks.POTATOES, lv2);
        map.put(Blocks.COMPARATOR, lv2);
        map.put(Blocks.ACTIVATOR_RAIL, lv2);
        map.put(Blocks.IRON_TRAPDOOR, lv2);
        map.put(Blocks.SUNFLOWER, lv2);
        map.put(Blocks.LILAC, lv2);
        map.put(Blocks.ROSE_BUSH, lv2);
        map.put(Blocks.PEONY, lv2);
        map.put(Blocks.TALL_GRASS, lv2);
        map.put(Blocks.LARGE_FERN, lv2);
        map.put(Blocks.SPRUCE_DOOR, lv2);
        map.put(Blocks.BIRCH_DOOR, lv2);
        map.put(Blocks.JUNGLE_DOOR, lv2);
        map.put(Blocks.ACACIA_DOOR, lv2);
        map.put(Blocks.CHERRY_DOOR, lv2);
        map.put(Blocks.DARK_OAK_DOOR, lv2);
        map.put(Blocks.PALE_OAK_DOOR, lv2);
        map.put(Blocks.MANGROVE_DOOR, lv2);
        map.put(Blocks.BAMBOO_DOOR, lv2);
        map.put(Blocks.COPPER_DOOR, lv2);
        map.put(Blocks.EXPOSED_COPPER_DOOR, lv2);
        map.put(Blocks.WEATHERED_COPPER_DOOR, lv2);
        map.put(Blocks.OXIDIZED_COPPER_DOOR, lv2);
        map.put(Blocks.WAXED_COPPER_DOOR, lv2);
        map.put(Blocks.WAXED_EXPOSED_COPPER_DOOR, lv2);
        map.put(Blocks.WAXED_WEATHERED_COPPER_DOOR, lv2);
        map.put(Blocks.WAXED_OXIDIZED_COPPER_DOOR, lv2);
        map.put(Blocks.END_ROD, lv2);
        map.put(Blocks.CHORUS_PLANT, lv2);
        map.put(Blocks.CHORUS_FLOWER, lv2);
        map.put(Blocks.TORCHFLOWER, lv2);
        map.put(Blocks.TORCHFLOWER_CROP, lv2);
        map.put(Blocks.PITCHER_PLANT, lv2);
        map.put(Blocks.PITCHER_CROP, lv2);
        map.put(Blocks.BEETROOTS, lv2);
        map.put(Blocks.KELP, lv2);
        map.put(Blocks.KELP_PLANT, lv2);
        map.put(Blocks.TURTLE_EGG, lv2);
        map.put(Blocks.DEAD_TUBE_CORAL, lv2);
        map.put(Blocks.DEAD_BRAIN_CORAL, lv2);
        map.put(Blocks.DEAD_BUBBLE_CORAL, lv2);
        map.put(Blocks.DEAD_FIRE_CORAL, lv2);
        map.put(Blocks.DEAD_HORN_CORAL, lv2);
        map.put(Blocks.TUBE_CORAL, lv2);
        map.put(Blocks.BRAIN_CORAL, lv2);
        map.put(Blocks.BUBBLE_CORAL, lv2);
        map.put(Blocks.FIRE_CORAL, lv2);
        map.put(Blocks.HORN_CORAL, lv2);
        map.put(Blocks.DEAD_TUBE_CORAL_FAN, lv2);
        map.put(Blocks.DEAD_BRAIN_CORAL_FAN, lv2);
        map.put(Blocks.DEAD_BUBBLE_CORAL_FAN, lv2);
        map.put(Blocks.DEAD_FIRE_CORAL_FAN, lv2);
        map.put(Blocks.DEAD_HORN_CORAL_FAN, lv2);
        map.put(Blocks.TUBE_CORAL_FAN, lv2);
        map.put(Blocks.BRAIN_CORAL_FAN, lv2);
        map.put(Blocks.BUBBLE_CORAL_FAN, lv2);
        map.put(Blocks.FIRE_CORAL_FAN, lv2);
        map.put(Blocks.HORN_CORAL_FAN, lv2);
        map.put(Blocks.DEAD_TUBE_CORAL_WALL_FAN, lv2);
        map.put(Blocks.DEAD_BRAIN_CORAL_WALL_FAN, lv2);
        map.put(Blocks.DEAD_BUBBLE_CORAL_WALL_FAN, lv2);
        map.put(Blocks.DEAD_FIRE_CORAL_WALL_FAN, lv2);
        map.put(Blocks.DEAD_HORN_CORAL_WALL_FAN, lv2);
        map.put(Blocks.TUBE_CORAL_WALL_FAN, lv2);
        map.put(Blocks.BRAIN_CORAL_WALL_FAN, lv2);
        map.put(Blocks.BUBBLE_CORAL_WALL_FAN, lv2);
        map.put(Blocks.FIRE_CORAL_WALL_FAN, lv2);
        map.put(Blocks.HORN_CORAL_WALL_FAN, lv2);
        map.put(Blocks.SEA_PICKLE, lv2);
        map.put(Blocks.CONDUIT, lv2);
        map.put(Blocks.BAMBOO_SAPLING, lv2);
        map.put(Blocks.BAMBOO, lv2);
        map.put(Blocks.POTTED_BAMBOO, lv2);
        map.put(Blocks.SCAFFOLDING, lv2);
        map.put(Blocks.STONECUTTER, lv2);
        map.put(Blocks.LANTERN, lv2);
        map.put(Blocks.SOUL_LANTERN, lv2);
        Blocks.COPPER_LANTERNS.forEach(arg2 -> map.put(arg2, lv2));
        map.put(Blocks.CAMPFIRE, lv2);
        map.put(Blocks.SOUL_CAMPFIRE, lv2);
        map.put(Blocks.SWEET_BERRY_BUSH, lv2);
        map.put(Blocks.WEEPING_VINES, lv2);
        map.put(Blocks.WEEPING_VINES_PLANT, lv2);
        map.put(Blocks.TWISTING_VINES, lv2);
        map.put(Blocks.TWISTING_VINES_PLANT, lv2);
        map.put(Blocks.NETHER_SPROUTS, lv2);
        map.put(Blocks.CRIMSON_FUNGUS, lv2);
        map.put(Blocks.WARPED_FUNGUS, lv2);
        map.put(Blocks.CRIMSON_ROOTS, lv2);
        map.put(Blocks.WARPED_ROOTS, lv2);
        map.put(Blocks.POTTED_CRIMSON_FUNGUS, lv2);
        map.put(Blocks.POTTED_WARPED_FUNGUS, lv2);
        map.put(Blocks.POTTED_CRIMSON_ROOTS, lv2);
        map.put(Blocks.POTTED_WARPED_ROOTS, lv2);
        map.put(Blocks.CRIMSON_DOOR, lv2);
        map.put(Blocks.WARPED_DOOR, lv2);
        map.put(Blocks.POINTED_DRIPSTONE, lv2);
        map.put(Blocks.SMALL_AMETHYST_BUD, lv2);
        map.put(Blocks.MEDIUM_AMETHYST_BUD, lv2);
        map.put(Blocks.LARGE_AMETHYST_BUD, lv2);
        map.put(Blocks.AMETHYST_CLUSTER, lv2);
        map.put(Blocks.CAVE_VINES, lv2);
        map.put(Blocks.CAVE_VINES_PLANT, lv2);
        map.put(Blocks.SPORE_BLOSSOM, lv2);
        map.put(Blocks.FLOWERING_AZALEA, lv2);
        map.put(Blocks.AZALEA, lv2);
        map.put(Blocks.PINK_PETALS, lv2);
        map.put(Blocks.WILDFLOWERS, lv2);
        map.put(Blocks.LEAF_LITTER, lv2);
        map.put(Blocks.BIG_DRIPLEAF, lv2);
        map.put(Blocks.BIG_DRIPLEAF_STEM, lv2);
        map.put(Blocks.SMALL_DRIPLEAF, lv2);
        map.put(Blocks.HANGING_ROOTS, lv2);
        map.put(Blocks.SCULK_SENSOR, lv2);
        map.put(Blocks.CALIBRATED_SCULK_SENSOR, lv2);
        map.put(Blocks.SCULK_VEIN, lv2);
        map.put(Blocks.SCULK_SHRIEKER, lv2);
        map.put(Blocks.MANGROVE_PROPAGULE, lv2);
        map.put(Blocks.FROGSPAWN, lv2);
        map.put(Blocks.COPPER_GRATE, lv2);
        map.put(Blocks.EXPOSED_COPPER_GRATE, lv2);
        map.put(Blocks.WEATHERED_COPPER_GRATE, lv2);
        map.put(Blocks.OXIDIZED_COPPER_GRATE, lv2);
        map.put(Blocks.WAXED_COPPER_GRATE, lv2);
        map.put(Blocks.WAXED_EXPOSED_COPPER_GRATE, lv2);
        map.put(Blocks.WAXED_WEATHERED_COPPER_GRATE, lv2);
        map.put(Blocks.WAXED_OXIDIZED_COPPER_GRATE, lv2);
        map.put(Blocks.FIREFLY_BUSH, lv2);
        map.put(Blocks.CACTUS_FLOWER, lv2);
        map.put(Blocks.BEACON, lv2);
        BlockRenderLayer lv3 = BlockRenderLayer.TRANSLUCENT;
        map.put(Blocks.ICE, lv3);
        map.put(Blocks.NETHER_PORTAL, lv3);
        map.put(Blocks.GLASS, lv3);
        map.put(Blocks.GLASS_PANE, lv3);
        map.put(Blocks.WHITE_STAINED_GLASS, lv3);
        map.put(Blocks.ORANGE_STAINED_GLASS, lv3);
        map.put(Blocks.MAGENTA_STAINED_GLASS, lv3);
        map.put(Blocks.LIGHT_BLUE_STAINED_GLASS, lv3);
        map.put(Blocks.YELLOW_STAINED_GLASS, lv3);
        map.put(Blocks.LIME_STAINED_GLASS, lv3);
        map.put(Blocks.PINK_STAINED_GLASS, lv3);
        map.put(Blocks.GRAY_STAINED_GLASS, lv3);
        map.put(Blocks.LIGHT_GRAY_STAINED_GLASS, lv3);
        map.put(Blocks.CYAN_STAINED_GLASS, lv3);
        map.put(Blocks.PURPLE_STAINED_GLASS, lv3);
        map.put(Blocks.BLUE_STAINED_GLASS, lv3);
        map.put(Blocks.BROWN_STAINED_GLASS, lv3);
        map.put(Blocks.GREEN_STAINED_GLASS, lv3);
        map.put(Blocks.REDSTONE_WIRE, lv3);
        map.put(Blocks.RED_STAINED_GLASS, lv3);
        map.put(Blocks.BLACK_STAINED_GLASS, lv3);
        map.put(Blocks.WHITE_STAINED_GLASS_PANE, lv3);
        map.put(Blocks.ORANGE_STAINED_GLASS_PANE, lv3);
        map.put(Blocks.MAGENTA_STAINED_GLASS_PANE, lv3);
        map.put(Blocks.LIGHT_BLUE_STAINED_GLASS_PANE, lv3);
        map.put(Blocks.YELLOW_STAINED_GLASS_PANE, lv3);
        map.put(Blocks.LIME_STAINED_GLASS_PANE, lv3);
        map.put(Blocks.PINK_STAINED_GLASS_PANE, lv3);
        map.put(Blocks.GRAY_STAINED_GLASS_PANE, lv3);
        map.put(Blocks.LIGHT_GRAY_STAINED_GLASS_PANE, lv3);
        map.put(Blocks.CYAN_STAINED_GLASS_PANE, lv3);
        map.put(Blocks.PURPLE_STAINED_GLASS_PANE, lv3);
        map.put(Blocks.BLUE_STAINED_GLASS_PANE, lv3);
        map.put(Blocks.BROWN_STAINED_GLASS_PANE, lv3);
        map.put(Blocks.GREEN_STAINED_GLASS_PANE, lv3);
        map.put(Blocks.RED_STAINED_GLASS_PANE, lv3);
        map.put(Blocks.BLACK_STAINED_GLASS_PANE, lv3);
        map.put(Blocks.SLIME_BLOCK, lv3);
        map.put(Blocks.HONEY_BLOCK, lv3);
        map.put(Blocks.FROSTED_ICE, lv3);
        map.put(Blocks.BUBBLE_COLUMN, lv3);
        map.put(Blocks.TINTED_GLASS, lv3);
    });
    private static final Map<Fluid, BlockRenderLayer> FLUIDS = Util.make(Maps.newHashMap(), map -> {
        map.put(Fluids.FLOWING_WATER, BlockRenderLayer.TRANSLUCENT);
        map.put(Fluids.WATER, BlockRenderLayer.TRANSLUCENT);
    });
    private static boolean cutoutLeaves;

    public static BlockRenderLayer getBlockLayer(BlockState state) {
        Block lv = state.getBlock();
        if (lv instanceof LeavesBlock) {
            return cutoutLeaves ? BlockRenderLayer.CUTOUT : BlockRenderLayer.SOLID;
        }
        BlockRenderLayer lv2 = BLOCKS.get(lv);
        if (lv2 != null) {
            return lv2;
        }
        return BlockRenderLayer.SOLID;
    }

    public static RenderLayer getMovingBlockLayer(BlockState state) {
        Block lv = state.getBlock();
        if (lv instanceof LeavesBlock) {
            return cutoutLeaves ? RenderLayers.cutout() : RenderLayers.solid();
        }
        BlockRenderLayer lv2 = BLOCKS.get(lv);
        if (lv2 != null) {
            return switch (lv2) {
                default -> throw new MatchException(null, null);
                case BlockRenderLayer.SOLID -> RenderLayers.solid();
                case BlockRenderLayer.CUTOUT -> RenderLayers.cutout();
                case BlockRenderLayer.TRANSLUCENT -> RenderLayers.translucentMovingBlock();
                case BlockRenderLayer.TRIPWIRE -> RenderLayers.tripwire();
            };
        }
        return RenderLayers.solid();
    }

    public static RenderLayer getEntityBlockLayer(BlockState state) {
        BlockRenderLayer lv = BlockRenderLayers.getBlockLayer(state);
        if (lv == BlockRenderLayer.TRANSLUCENT) {
            return TexturedRenderLayers.getBlockTranslucentCull();
        }
        return TexturedRenderLayers.getEntityCutout();
    }

    public static BlockRenderLayer getFluidLayer(FluidState state) {
        BlockRenderLayer lv = FLUIDS.get(state.getFluid());
        if (lv != null) {
            return lv;
        }
        return BlockRenderLayer.SOLID;
    }

    public static void setCutoutLeaves(boolean cutoutLeaves) {
        BlockRenderLayers.cutoutLeaves = cutoutLeaves;
    }
}

